### ISSUE TITLE
DevTools persistState debug session

### ISSUE THREAD

**Issue by Hyra** [caljrimmer/simple-redux-boiler#2]
I really like this structure, well done.

I have one issue with dev tools however. When enabling debug_session with 

`persistState(window.location.href.match(/[?&]debug_session=([^&]+)\b/))`

I get console warnings:

`Could not write debug session to localStorage: TypeError: Converting circular structure to JSON(…)`

Any idea how this can be solved?

**Comment by caljrimmer** [comment]
I spent a few hours this evening looking over this. There are a couple of issues with using persistState in this boilerplate.

The first is that Redux router has circular paths in its state object. That is what is triggering your console warning and stopping the state writing to localStorage.

The second is the state data accumulated by the undo/redo functionality (persists multiple copies of state), in addition to the data received via the ajax calls. This quickly exceeds what you can store in local storage (i.e. exceeded the quota).

So to get working i would suggest:
- Remove Redux Router
- Remove undo/redo functionality from postsByReddit (I will probably do this anyway as it will hog memory with DevTools open)

Putting persistState() before DevTools() in the middleware will lessen what is written to localStorage. This decrements the usefulness of persistState with DevTools though but will still persist application state.

Hope this helps.

**Comment by Hyra** [comment]
Heya, i decided to strip the boilerplate down and migrate to the latest versions of react/devtools/etc.

That, combined with removing undoable, makes everything work again.

If you're interested, I put that version up here https://github.com/Hyra/Antler

**Comment by caljrimmer** [comment]
I have a branch with React 0.14 version working with DevTools 3.0.0 beta on it (branch react-upgrade-0.14), I will re-test the issue on that.

Looks good. Thanks Hyra

**Comment by Hyra** [comment]
In case you stumble upon this issue: the current log monitor uses a browser reference, which causes issues at the server rendering (everything seems to be working, but its not rendered universal)

"Solved" this by checking for browser before injecting DevTools

**Comment by tnrich** [comment]
@caljrimmer @Hyra , I'm running into the same issue:

![image](https://cloud.githubusercontent.com/assets/2730609/20772350/fea3f1a2-b701-11e6-8752-ec9b8d4bdd0a.png)

I am using redux-router in my app, do you think this is being caused by the router?

I'm also storing pretty large blobs of data in my state. If that is the cause instead, how should I go about fixing that?
