### ISSUE TITLE
website down

### ISSUE THREAD

**Issue by International** [caljrimmer/simple-redux-boiler#3]
Hi, I saw a link to your website from react.rocks , and I wanted to see how the website looks online. However, there's a 502 Bad Gateway when visiting it :)

**Comment by caljrimmer** [comment]
Hi George,

Thanks for the email. I have re-started my server. Annoyingly I should 
be emailed when the server is down but I shall investigate the reason.

Many thanks,
Callum

On 29/12/2015 12:29, George Opritescu wrote:

> Hi, I saw a link to your website from reactrocks , and I wanted to see 
> how the website looks online However, there's a 502 Bad Gateway when 
> visiting it :)
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/caljrimmer/isomorphic-redux-app/issues/3.

## 

_Callum Rimmer_
Freelance Full Stack JavaScript Developer
..............................................................
http://www.callumrimmer.co.uk
Mobile // 07919 411 405
GitHub // https://github.com/caljrimmer
Linkedin // https://www.linkedin.com/in/callumrimmer
