### ISSUE TITLE
An error occur when i try to start it with npm start 

### ISSUE THREAD

**Issue by BobLamarley** [caljrimmer/simple-redux-boiler#7]
Hi,
Here is the attach file showing the error, i'm on windows so i've tried to change NODE_ENV= with set NODE_ENV= but it didn't work.
I don't understand why i have this error 
![untitled](https://cloud.githubusercontent.com/assets/7857364/14767328/ffe3b2d2-0a22-11e6-8988-f3fa7f9155d8.png)
Thnak you in advance for help :)

**Comment by caljrimmer** [comment]
Try using SET and && between each statement declaration. i.e. 

SET NODE_ENV=development && node src/server/index.js

**Comment by BobLamarley** [comment]
It works. Thank you :)

**Comment by caljrimmer** [comment]
NP.
